version: '2'
services:
  # web:
  #   build: .
  #   command: bin/rails server -e docker --port 3000 --binding 0.0.0.0
  #   environment:
  #     RAILS_ENV: 'development'
  #     RACK_ENV: 'development'
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - db
  #   volumes:
  #     - .:/app
  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   environment:
  #     RAILS_ENV: 'development'
  #     RACK_ENV: 'development'
  #   ports:
  #     - "3000:3000"
  #   links:
  #     - db
  #   volumes:
  #     - .:/app
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'oddesign'
      POSTGRES_PASSWORD: 'qwerasdf'
    volumes:
      - './docker_data/postgres:/var/lib/postgresql/data'
  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - './docker_data/redis:/var/lib/redis/data'
